Traceback (most recent call last):
  File "resnet50_3d_charades_continue.py", line 57, in <module>
    main()
  File "/data/stars/user/sdas/PyVideoResearch/main.py", line 90, in main
    scores.update(validate(trainer, val_loader, model, criterion, args, metrics, tasks, epoch))
  File "/data/stars/user/sdas/PyVideoResearch/main.py", line 40, in validate
    scores.update(task.run(model, criterion, epoch, args))
  File "/data/stars/user/sdas/PyVideoResearch/tasks/video_task.py", line 17, in run
    return task.validate_video(loader, model, criterion, epoch, args)
  File "/data/stars/user/sdas/PyVideoResearch/tasks/video_task.py", line 29, in validate_video
    for i, (input, target, meta) in enumerate(loader):
  File "/home/sdas/anaconda2/envs/torch_4/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 280, in __next__
    idx, batch = self._get_batch()
  File "/home/sdas/anaconda2/envs/torch_4/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 259, in _get_batch
    return self.data_queue.get()
  File "/home/sdas/anaconda2/envs/torch_4/lib/python3.6/multiprocessing/queues.py", line 335, in get
    res = self._reader.recv_bytes()
  File "/home/sdas/anaconda2/envs/torch_4/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/sdas/anaconda2/envs/torch_4/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/sdas/anaconda2/envs/torch_4/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/home/sdas/anaconda2/envs/torch_4/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 178, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 15414) is killed by signal: Killed.
